services:
  postgres:
    image: postgres:16
    container_name: hackkosice-postgres
    environment:
      POSTGRES_DB: hackkosice
      POSTGRES_USER: hackkosice
      POSTGRES_PASSWORD: hackkosice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: